---
- name: Deploy ldap_conf.ini 
  template: src=ldap_conf.ini dest=/etc/opush/ldap_conf.ini
  tags: opush

- name: Deploy cassandra.ini 
  template: src=cassandra.ini dest=/etc/opush/cassandra.ini
  tags: opush

- name: Deploy opush.ini 
  template: src=opush.ini dest=/etc/opush/opush.ini
  tags: opush

- name: Deploy logback.xml
  template: src=logback.xml dest=/etc/opush/logback.xml
  notify: 
      - Restart OPush
  tags: opush

- name: Fix perms on obm_conf.ini
  file: path=/etc/opush/{{ item }} mode=0644
  with_items:
   - ldap_conf.ini
   - logback.xml
   - cassandra.ini
   - opush.ini
  tags: opush
