---
sasl_ldap_port: "{{ custom_sasl_ldap_port | default('unspecified') }}"
sasl_ldap_host: "{{ custom_sasl_ldap_host | default('unspecified') }}"
sasl_ldap_ssl: "{{ custom_sasl_ldap_ssl | default('no') }}"
